import Link from "next/link";
import "./globals.css"; //전역 디자인 파일
import { Control } from "./Control";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by yuel",
};

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
    cache: "no-store", // 0초
  });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">Web</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
